# See https://github.com/jerryc127/hexo-theme-butterfly/blob/dev/_config.yml
# https://github.com/jerryc127/butterfly.js.org/blob/main/_config.butterfly.yml

# Default display mode (網站默認的顯示模式)
# light (default) / dark
display_mode: dark

# Menu 目錄
menu:
  Home: / || fas fa-home
  Archives: /archives/ || fas fa-archive
  Tags: /tags/ || fas fa-tags
  # Categories: /categories/ || fas fa-folder-open
  # Link: /link/ || fas fa-link
  # About: /about/ || fas fa-heart

social:
  # fab fa-github: https://github.com/lawvs || Github
  fas fa-envelope: mailto:me@waterwater.moe || Email
  fas fa-rss: /atom.xml || RSS

# Image (圖片設置)
# --------------------------------------

# Favicon（網站圖標）
favicon: /favicon.png

# Avatar (頭像)
avatar:
  img: /static/avatar.jpg
  effect: false

# Disable all banner image
disable_top_img: true

post_meta:
  page: # Home Page
    tags: true # true or false 主頁是否顯示標籤

footer:
  owner:
    enable: true
    since: 2017

# aside (側邊欄)
# --------------------------------------

aside:
  enable: true
  display:
    archive: true
    tag: true
    category: false
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: GitHub
      link: https://github.com/lawvs
  card_announcement:
    enable: false
  card_categories:
    enable: false

# busuanzi count for PV / UV in site
# 訪問人數
busuanzi:
  site_uv: false
  site_pv: false
  page_pv: false

# wordcount (字數統計)
# see https://butterfly.js.org/posts/ceeb73f/#字數統計
# pnpm add hexo-wordcount --save
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

pangu:
  enable: true

canvas_ribbon:
  enable: true

# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# 插入代码到头部 </head> 之前 和 底部 </body> 之前
inject:
  head:
    - <link rel="stylesheet" href="/static/custom.css">
